version: "1"

services:
  - type: web
    name: tomatoes-backend
    env: python
    plan: free
    runtime: python-3.10
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python download_model.py && python app.py"
